#pragma once

/* Wi-Fi热点名称 */
#define WIFI_SSID               CONFIG_APP_WIFI_SSID
/* Wi-Fi热点密码 */
#define WIFI_PASSWORD           CONFIG_APP_WIFI_PASSWORD
/* Wi-Fi最大重连次数 */
#define WIFI_MAXIMUM_RETRY      CONFIG_APP_WIFI_MAXIMUM_RETRY

/* OneNET MQTT服务器地址 */
#define ONENET_HOST             CONFIG_APP_ONENET_HOST
/* OneNET Token版本号 */
#define ONENET_VERSION          CONFIG_APP_ONENET_VERSION
/* OneNET Token签名算法 */
#define ONENET_METHOD           CONFIG_APP_ONENET_METHOD
/* OneNET Token过期时间戳 */
#define ONENET_TOKEN_EXPIRY     CONFIG_APP_ONENET_TOKEN_EXPIRY

/* OneNET产品ID */
#define ONENET_PRODUCT_ID       CONFIG_APP_ONENET_PRODUCT_ID
/* OneNET设备名称 */
#define ONENET_DEVICE_NAME      CONFIG_APP_ONENET_DEVICE_NAME
/* OneNET设备密钥 */
#define ONENET_DEVICE_KEY       CONFIG_APP_ONENET_DEVICE_KEY

/* UART端口号 */
#define APP_UART_PORT_NUM       CONFIG_APP_UART_PORT
/* UART波特率 */
#define APP_UART_BAUD_RATE      CONFIG_APP_UART_BAUD_RATE
/* UART发送引脚 */
#define APP_UART_TX_PIN         CONFIG_APP_UART_TX_PIN
/* UART接收引脚 */
#define APP_UART_RX_PIN         CONFIG_APP_UART_RX_PIN
/* UART缓冲区大小 */
#define APP_UART_BUFFER_SIZE    CONFIG_APP_UART_BUFFER_SIZE
